version: '3.8'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine
    expose:
      - 6379
#
#version: '3.8'
#
#services:
#  web:
#    build: ./
#    command: python manage.py runserver  0.0.0.0:8000
#    volumes:
#      - ./:/usr/src/app/
#    ports:
#      - 8000:8000
#    env_file:
#      - ./.venv/dev
#    depends_on:
#      - db
#  db:
#    image: postgres:15
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=ilhom
#      - POSTGRES_DB=kutubxona
#
#volumes:
#  postgres_data: