# Generated by Django 5.0.3 on 2024-03-07 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitoblar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='content',
            new_name='text',
        ),
    ]
