# Generated by Django 5.0.3 on 2024-03-07 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitoblar', '0002_rename_content_book_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='blog',
            new_name='book',
        ),
    ]
